vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.tabstop = 2
vim.opt.wrap = false
vim.opt.colorcolumn = "90"
vim.g.mapleader = " "
